### ISSUE TITLE
<back Home. looks a bit off in _layouts post.html

### ISSUE THREAD

**Issue by SoumitraAgarwal** [renyuanz/leonids#14]
Just by the perspective of how it looks, the link looks a bit odd. We might change it to < Home or changing the font might help.

**Comment by renyuanz** [comment]
Yeah, you are right. gonna change this.

**Comment by SoumitraAgarwal** [comment]
Do you want me to try something and create a pull request?

**Comment by renyuanz** [comment]
This is referenced to PR #18 

@SoumitraAgarwal don't you think it's better to use `btn` class instead of creating a new style ?

By adding `btn` directly to `a` element : 

``` html
<a class="btn" href="http://renyuanz.github.io/leonids/">
  Home
</a>
```

and we get this 

<img width="297" alt="screen shot 2016-05-23 at 11 03 21" src="https://cloud.githubusercontent.com/assets/10615036/15466363/809f06fc-20d9-11e6-99d4-8e884c3d6d49.png">

**Comment by SoumitraAgarwal** [comment]
Yes, I think that would be a good idea, since we are using solid buttons for the `sharing` panel. Assign this to me?

**Comment by renyuanz** [comment]
Yes please :)

Really appreciate your contribution to this project !

**Comment by renyuanz** [comment]
#19
